---
deployment:
  tasks:
    - export DEPLOYPATH=/home/plyapitechiesqua/laravel
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
    - php artisan key:generate --force
    - php artisan migrate --force
    - php artisan optimize:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:clear
